"""وصف التغيير

Revision ID: 71e50030365e
Revises: b9801f6d162c
Create Date: 2026-10-05 00:05:20.944268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e50030365e'
down_revision = 'b9801f6d162c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=32), nullable=False),
    sa.Column('citizen_name', sa.String(length=120), nullable=False),
    sa.Column('citizen_phone', sa.String(length=32), nullable=False),
    sa.Column('report_kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('complaint_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_citizen_phone'), ['citizen_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_reference_number'), ['reference_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_complaints_report_kind'), ['report_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_report_kind'))
        batch_op.drop_index(batch_op.f('ix_complaints_reference_number'))
        batch_op.drop_index(batch_op.f('ix_complaints_citizen_phone'))
        batch_op.drop_index(batch_op.f('ix_complaints_category'))

    op.drop_table('complaints')
    # ### end Alembic commands ###
